name: We All Bleed
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#eaddcd'
    - '#96794f'
    - '#37240d'
    - '#6f512a'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
