name: We All Bleed
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6c6c6c'
    - '#313131'
    - '#858585'
    - '#151515'
    - '#a2a2a2'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
